# docker image for mrvl vs syncd

DOCKER_SYNCD_MRVL_VS = docker-syncd-mrvl-vs.gz

$(DOCKER_SYNCD_MRVL_VS)_PATH = $(PLATFORM_PATH)/docker-syncd-mrvl-vs
$(DOCKER_SYNCD_MRVL_VS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
$(DOCKER_SYNCD_MRVL_VS)_DEPENDS += $(MRVL_VS_SAI) $(SYNCD)

ifeq ($(INSTALL_DEBUG_TOOLS), y)
$(DOCKER_SYNCD_MRVL_VS)_DEPENDS += $(SYNCD_DBG) \
                                    $(LIBSWSSCOMMON_DBG) \
                                    $(LIBSAIMETADATA_DBG) \
                                    $(LIBSAIREDIS_DBG)
endif
$(DOCKER_SYNCD_MRVL_VS)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)
$(DOCKER_SYNCD_MRVL_VS)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_SYNCD_MRVL_VS)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_VS)
ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_VS)
endif

$(DOCKER_SYNCD_MRVL_VS)_VERSION = 1.0.0
$(DOCKER_SYNCD_MRVL_VS)_PACKAGE_NAME = syncd-vs
$(DOCKER_SYNCD_MRVL_VS)_MACHINE = marvell-vs
$(DOCKER_SYNCD_MRVL_VS)_AFTER = $(DOCKER_SYNCD_BASE)
$(DOCKER_SYNCD_MRVL_VS)_CONTAINER_NAME = syncd
$(DOCKER_SYNCD_MRVL_VS)_RUN_OPT += --privileged -t
$(DOCKER_SYNCD_MRVL_VS)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_SYNCD_MRVL_VS)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SYNCD_MRVL_VS)_RUN_OPT += -v /host/warmboot:/var/warmboot

SONIC_BULLSEYE_DOCKERS += $(DOCKER_SYNCD_MRVL_VS)
