# docker image for mrvl prestera syncd

DOCKER_SYNCD_MRVL_PRESTERA = docker-syncd-mrvl-prestera.gz

$(DOCKER_SYNCD_MRVL_PRESTERA)_PATH = $(PLATFORM_PATH)/docker-syncd-mrvl-prestera
$(DOCKER_SYNCD_MRVL_PRESTERA)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
$(DOCKER_SYNCD_MRVL_PRESTERA)_DEPENDS += $(MRVL_SAI) $(SYNCD)

ifeq ($(INSTALL_DEBUG_TOOLS), y)
$(DOCKER_SYNCD_MRVL_PRESTERA)_DEPENDS += $(SYNCD_DBG) \
					$(LIBSWSSCOMMON_DBG) \
					$(LIBSAIMETADATA_DBG) \
					$(LIBSAIREDIS_DBG)
endif
$(DOCKER_SYNCD_MRVL_PRESTERA)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)
$(DOCKER_SYNCD_MRVL_PRESTERA)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_SYNCD_MRVL_PRESTERA)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_PRESTERA)
ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_PRESTERA)
endif

$(DOCKER_SYNCD_MRVL_PRESTERA)_VERSION = 1.0.0
$(DOCKER_SYNCD_MRVL_PRESTERA)_PACKAGE_NAME = syncd-prestera
$(DOCKER_SYNCD_MRVL_PRESTERA)_MACHINE = marvell-prestera
$(DOCKER_SYNCD_MRVL_PRESTERA)_AFTER = $(DOCKER_SYNCD_BASE)
$(DOCKER_SYNCD_MRVL_PRESTERA)_CONTAINER_NAME = syncd
$(DOCKER_SYNCD_MRVL_PRESTERA)_RUN_OPT += --privileged -t
$(DOCKER_SYNCD_MRVL_PRESTERA)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_SYNCD_MRVL_PRESTERA)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SYNCD_MRVL_PRESTERA)_RUN_OPT += -v /host/warmboot:/var/warmboot

SONIC_BULLSEYE_DOCKERS += $(DOCKER_SYNCD_MRVL_PRESTERA)
